Merged revision(s) 4941-4945, 4947-4966 from branches/testing-7.3: *7.2* Compiler options-related defines cleanup: - Added global OverFlowCheckEnabled define to generic include file - All local compiler options-related defines removed in favor of generic RangeCheckEnabled and OverFlowCheckEnabled ........ *7.2* Compiler options-related defines cleanup for lists and collection: - Checks are enabled by DISABLE_CHECKING define instead of RangeCheck (that is what DISABLE_CHECKING is intended for) - internal ReturnAddr functions replaced with intrinsic ReturnAddress (available since XE2); older versions use ZCompatibility.ReturnAddress which was made available for non-asm compilation too. ........ *7.2* Added StreamFromData functions to shorten stream creation. ........ *7.2* Finally resolved internal error C1118 bug on D7 without complete disabling of range check. ........ 7.2: Fix for the new proxy FindCmdLineSwitch function - it called the sysutils function but never used the result.. ........ *7.2* IFNDEF UNIX => IFDEF MSWINDOWS which is more correct (MacOS, Linux, Android etc are not Unix) ........ *7.2* Removed usage of OLD_FPC define, cleanup of uses section ........ *7.2* (Lazarus) test suite project optimizations: - uses section cleanup - predefined Run parameters removed - path to fpcunit removed from SearchPath. It was useless and made compiler rebuild all fpcunit units every time the project was rebuilt. - all available check and debug options enabled ........ *7.2* Started activity on removing globally disabled warnings and hints. Idea is to disable only specific hints and as minimally as possible. Thus compiler will help finding bugs. ........ *7.2* TZAbstractRODataset.GetActiveBuffer, TZAbstractPreparedStatement2.Get*, IZConnection.Get(Binary)EscapeString - result parameter declared as "out" instead of "var" (this eliminated many "variable not init'd" warnings)
........
*7.2* More hints/warnings stuff - now for drivers. Currently compiler will print messages regarding deprecated constructors.
........
*7.2* More warnings stuff. This helped to fix usage of deprecated Thread.Resume and forgotten result assignment in TZQuoteState.DecodeString
........
*7.2* Defines cleanup: HAVE_TBYTES, WITH_EARGUMENTEXCEPTION, MISS_VARIANTCLEAR replaced with IF DECLARED; WITH_FPC_STRING_CONVERSATION => WITH_FPC_STRING_CONVERSION; unused MULTI_THREADED, USELIBFBCLIENTSO, USE_SYNEDIT commented out and marked with TODO
........
*7.2* BytesOf seems not used by any unit ?? Removed for now; anyway one could use ZSysUtils.BufferToBytes instead
........
*7.2* Cosmetic change: removed ifdefs inside ADO and OleDB units. If these drivers are disabled, they shouldn't be used at all so ifdefs inside are excessive.
........
*7.2* Remove warnings disabling for drivers pt.2
........
*7.2* More hints enabling. Disabled WARN 4056 as well. more "var" parameters declared as "out"
........
*7.2* more "var" parameters declared as "out"
*7.2* (FPC) Warnings hunt. Added definition of WITH_ASANSISTRING and new define WITH_ASUTF8STRING (3.0.2+)
*7.2* more "var" parameters declared as "out"
Merged revision(s) 4941-4945, 4947-4966 from branches/testing-7.3:
*7.2* Compiler options-related defines cleanup:
- Added global OverFlowCheckEnabled define to generic include file
- All local compiler options-related defines removed in favor of generic RangeCheckEnabled and OverFlowCheckEnabled
........
*7.2* Compiler options-related defines cleanup for lists and collection:
- Checks are enabled by DISABLE_CHECKING define instead of RangeCheck (that is what DISABLE_CHECKING is intended for)
- internal ReturnAddr functions replaced with intrinsic ReturnAddress (available since XE2); older versions use ZCompatibility.ReturnAddress which was made available for non-asm compilation too.
........
*7.2* Added StreamFromData functions to shorten stream creation.
........
*7.2* Finally resolved internal error C1118 bug on D7 without complete disabling of range check.
........
7.2: Fix for the new proxy FindCmdLineSwitch function - it called the sysutils function but never used the result..
........
*7.2* IFNDEF UNIX => IFDEF MSWINDOWS which is more correct (MacOS, Linux, Android etc are not Unix)
........
*7.2* Removed usage of OLD_FPC define, cleanup of uses section
........
*7.2* (Lazarus) test suite project optimizations:
- uses section cleanup
- predefined Run parameters removed
- path to fpcunit removed from SearchPath. It was useless and made compiler rebuild all fpcunit units every time the project was rebuilt.
- all available check and debug options enabled
........
*7.2* Started activity on removing globally disabled warnings and hints. Idea is to disable only specific hints and as minimally as possible. Thus compiler will help finding bugs.
........
*7.2* TZAbstractRODataset.GetActiveBuffer, TZAbstractPreparedStatement2.Get*, IZConnection.Get(Binary)EscapeString - result parameter declared as "out" instead of "var" (this eliminated many "variable not init'd" warnings)

........
*7.2* More hints/warnings stuff - now for drivers. Currently compiler will print messages regarding deprecated constructors.
........
*7.2* More warnings stuff. This helped to fix usage of deprecated Thread.Resume and forgotten result assignment in TZQuoteState.DecodeString
........
*7.2* Defines cleanup: HAVE_TBYTES, WITH_EARGUMENTEXCEPTION, MISS_VARIANTCLEAR replaced with IF DECLARED; WITH_FPC_STRING_CONVERSATION => WITH_FPC_STRING_CONVERSION; unused MULTI_THREADED, USELIBFBCLIENTSO, USE_SYNEDIT commented out and marked with TODO
........
*7.2* BytesOf seems not used by any unit ?? Removed for now; anyway one could use ZSysUtils.BufferToBytes instead
........
*7.2* Cosmetic change: removed ifdefs inside ADO and OleDB units. If these drivers are disabled, they shouldn't be used at all so ifdefs inside are excessive.
........
*7.2* Remove warnings disabling for drivers pt.2
........
*7.2* More hints enabling. Disabled WARN 4056 as well. more "var" parameters declared as "out"
........
*7.2* more "var" parameters declared as "out"
........
*7.2* (FPC) Warnings hunt. Added definition of WITH_ASANSISTRING and new define WITH_ASUTF8STRING (3.0.2+)
........
*7.2* more "var" parameters declared as "out"
........
7.2: moved the check for EArgumentException. Placing it right behind the uses clause triggers "Internal error 200501152" on FPC 2.6
........
7.2: Add some ifdefs that reenable using infinity an neginfinity on FPC 2.6 with range checks enabled. Just using them without ifdefs will throw an compiler error: "Range check error while evaluating constants". Strange.
........
*7.2* More warnings hunt. FPC warnings are disabled on minimal possible areas with PUSH/POP technique (thus respecting project-defined options)
........
*7.2* Removed per-unit warning switching as they're disabled globally
........
*7.2* Re-enabled ZTestCompADOBugReport for FPC. What was the reason for its disabling?
........

7.2: moved the check for EArgumentException. Placing it right behind the uses clause triggers "Internal error 200501152" on FPC 2.6
........
7.2: Add some ifdefs that reenable using infinity an neginfinity on FPC 2.6 with range checks enabled. Just using them without ifdefs will throw an compiler error: "Range check error while evaluating constants". Strange.
*7.2* More warnings hunt. FPC warnings are disabled on minimal possible areas with PUSH/POP technique (thus respecting project-defined options)
*7.2* Removed per-unit warning switching as they're disabled globally
*7.2* Re-enabled ZTestCompADOBugReport for FPC. What was the reason for its disabling?


git-svn-id: http://svn.code.sf.net/p/zeoslib/code-0/branches/7.2-patches@5034 d681b350-854c-439c-a81d-c0ce20710203